# Generated by Django 4.0.6 on 2022-07-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_brand_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
    ]
