# Generated by Django 4.0.6 on 2022-07-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_image_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LAP', 'Laptop'), ('DPC', 'Desktop PC'), ('NET', 'Networking Device'), ('P&S', 'Printer and Scanner'), ('PCP', 'PC Port'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
